version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    ports:
      - '3001:3001'
    env_file:
      - apps/auth/.env
    depends_on:
      - mongo

  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - apps/gateway/.env
    depends_on:
      - auth

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    ports:
      - '3002:3002'
    env_file:
      - apps/event/.env
    depends_on:
      - mongo

volumes:
  mongo-data:
